### ISSUE TITLE
Borderlands 2 [30898]: No longer able to join games via RPCS3

### ISSUE THREAD

**Issue by Shoegzer** [RipleyTom/rpcn#101]
When attempting to join a game, the message "Connection failed: could not connect to host" appears.  This was working in RPCS3 about a week ago.

Test info:

System 1: 
* OS: Linux Mint 22.1 / kernel 6.11
* CPU: Intel i9-14900HX
* RPCS3 Commit: 0e5014788b316cafa8a45b8c7a05d9f3f5301bc9

System 2: 
* OS: Windows 11 Home
* CPU: Intel 17 13th Gen
* RPCS3 Commit: ec3d9a2cae5d5603d06efd9a9274a696874f905d

**Comment by RipleyTom** [comment]
Hopefully https://github.com/RPCS3/rpcs3/pull/16725 fixes it.

**Comment by Shoegzer** [comment]
Thanks for such a quick turnaround.  I'm building RPCS3 with the PR myself to try on my (Linux) end.  How would the Windows user I'm testing with be able to download a precompiled build with your PR for testing?

**Comment by Kayinnasaki** [comment]
Just wanted to add the Street Fighter 2: HD Remix also doesn't work. Hoping this is also fixed by the PR.

**Comment by Shoegzer** [comment]
Update: My build just finished though I'm not sure how my Windows user would get a build for testing.  Regardless, I tried Borderlands 2 which doesn't work, though with only one of us using this PR I don't know if the test results are helpful or meaningful.

**Comment by MSuih** [comment]
@Shoegzer you can download artifacts that the CI compiles, just view details on one of the builds and click around until you find the downloads section

**Comment by Shoegzer** [comment]
Okay, well we did eventually find the build so both of us have this PR now, but testing against Borderlands 2 we still get the same connection failed message.

**Comment by RipleyTom** [comment]
Tested SF2HD Turbo and Ultra Street Fighter IV and both work with the PR.

**Comment by Shoegzer** [comment]
Ultra Street Fighter IV does not work for either of us here, nor Fat Princess or Borderlands 2.  We're both using commit ec3d9a2cae5d5603d06efd9a9274a696874f905d with PR #16725 merged.  In the case of Ultra Street Fighter IV, any attempts by the Windows RPCN3 build to join a game by the Linux host cause the Windows build to crash.  In Fat Princess, the "Play With Others" option leads to "Probing Network" and eventually "Oh dear, your connection has been lost".  However, games such as Killzone 2 continue to work fine.

Recently as noted above, all of the above titles were working with RPCN.  Has anything changed in requirements for RPCN to function as normal? @Kayinnasaki can you test on your end and report results?

**Comment by Shoegzer** [comment]
Update: Here is the log from an Ultra Street Fighter IV session, showing Linux RPCS3 crashing when attempting to connect to a "Ranked Match" game started from a Windows system.  

Excerpt:
```
·! 0:06:33.335327 {TID: 110088} rpcn: recv failed: connection reset by server
·E 0:06:33.335341 {TID: 110088} rpcn: Disconnected
```
Full log: [RPCS3.log](https://github.com/user-attachments/files/18859747/RPCS3.log)

**Comment by RipleyTom** [comment]
Need retesting after server fix(live).

**Comment by Shoegzer** [comment]
Thanks. I tested Fat Princess with RPCN official just now, but had the same results as above.  The others I can retest when I have another participant handy, give me a day or so.

Log from Fat Princess session: [RPCS3.log](https://github.com/user-attachments/files/18923891/RPCS3.log)

**Comment by Shoegzer** [comment]
Good news, Borderlands 2 and Ultra Street Fighter IV are working fine now.  We tested Payday and Bodycount as well, both of which are working too (in fact, Bodycount seems to be working better than before, with a more consistent ability to join matches).  

Also: in Fat Princess, if you ignore the "lost connection" message, you can actually join games and play them, so the only remaining issue is the lost connection message itself.

**Comment by Kayinnasaki** [comment]
HDR confirmed working again, thank you!

**Comment by RADIOACTIVEshrek** [comment]
> Can you be more specific - do you mean bodycount pvp is still not working?

PvP is still not working on my end, that's correct. Coop public matches are the only thing that worked for me and my friend, whereas PvP gave the same sorts of bugs and errors as previously.

**Comment by Ninetime** [comment]
Hello is this still an issue?

**Comment by Ninetime** [comment]
@RADIOACTIVEshrek is this after testing with the latest build? There were several RPCN changes in the last few.
